- apps/auth-front/src/pages/confirm/ConfirmEmailPage.tsx
https://user-images.githubusercontent.com/67622360/199986301-9bb5594b-315c-49ad-b552-223a5a50e2e7.mp4
> 192 fix markup auth confirm page

- .github/workflows/e2e.yml
- .github/workflows/pr.yml
Pipeline does not work due to version of @playwright/test is not compatible with version of npx playwright/browsers
> [#243] fix e2e pipelines

- README.md
> [#265] Add maintainability codeclimate badge

- packages/ui/README.md
- packages/ui/package.json
- tsconfig.json
- typings/mui-theme-fix.d.ts
- yarn.lock
> [202]: Remove @mui/styles and clsx from ui package

- apps/ligretto-frontend/src/components/blocks/game/ScreenCountdown/ScreenCountdown.stories.tsx
- apps/ligretto-frontend/src/components/blocks/game/ScreenCountdown/ScreenCountdown.tsx
- apps/ligretto-frontend/src/components/blocks/game/ScreenCountdown/index.ts
- apps/ligretto-frontend/src/components/layouts/base/BaseLayout.module.scss
- apps/ligretto-frontend/src/components/layouts/base/BaseLayout.tsx
- apps/ligretto-frontend/src/components/layouts/main/MainLayout.module.scss
- apps/ligretto-frontend/src/components/layouts/main/MainLayout.tsx
- apps/ligretto-frontend/src/containers/game-page/GamePageContainer.selector.ts
- apps/ligretto-frontend/src/containers/game-page/GamePageContainer.tsx
- apps/ligretto-frontend/src/ducks/game/selectors.ts
- apps/ligretto-frontend/src/ducks/game/slice.ts
- apps/ligretto-gameplay-backend/src/controllers/__tests__/__snapshots__/games-contoller.spec.ts.snap
- apps/ligretto-gameplay-backend/src/controllers/gameplay-controller.ts
- apps/ligretto-gameplay-backend/src/entities/game/game.service.ts
- apps/ligretto-gameplay-backend/src/utils/wait.ts
- packages/ligretto-shared/src/types.ts
https://user-images.githubusercontent.com/22221382/220626356-21bc7881-3bf4-4e79-9402-c57d3130a8a4.mov
> [#272] Ligretto. Show countdown before start round

- .github/workflows/e2e.yml
- e2e/tests/game.spec.ts
> [#302]: Fix ligretto e2e

- .docker/GameHub-client_Dockerfile
- apps/gamehub-client/next.config.js
- apps/gamehub-client/package.json
- apps/gamehub-client/src/app/layout.tsx
- yarn.lock
> [EXPERIMENTAL]: Use standalone build for GameHub-client

- apps/auth-front/package.json
- apps/blog/package.json
- apps/blog/src/app/[locale]/layout.tsx
- apps/blog/src/components/LanguageSwitcher/Dropdown.tsx
- apps/blog/src/components/LanguageSwitcher/LanguageSwitcher.tsx
- apps/blog/src/components/LanguageSwitcher/index.ts
- apps/blog/src/i18n/locales/en/common.json
- apps/blog/src/i18n/locales/ru/common.json
- apps/blog/tailwind.config.js
- apps/gamehub-client/package.json
- apps/ligretto-frontend/package.json
- apps/ligretto-gameplay-backend/package.json
- package.json
- packages/analytics/package.json
- packages/ligretto-shared/package.json
- packages/ui/package.json
- yarn.lock
> [321]: Add language switcher. Up typescript

- apps/blog/src/app/[locale]/page.tsx
- apps/blog/src/app/[locale]/posts/[slug]/page.tsx
- apps/blog/src/app/[locale]/posts/layout.tsx
- apps/blog/src/app/[locale]/posts/page.tsx
- apps/blog/src/components/Breadcrumbs/Breadcrumbs.tsx
- apps/blog/src/components/Breadcrumbs/index.ts
- apps/blog/src/i18n/locales/en/posts.json
- apps/blog/src/i18n/locales/ru/posts.json
> [332]: Add Breadcrumbs

- apps/auth-front/src/pages/register/RegisterPage.tsx
- apps/auth-front/src/utils/i18n.ts
> [226] Fix sign up form errors

- apps/auth-front/src/pages/register/RegisterPage.tsx
> [348] Fix registration comfirm route

- apps/ligretto-frontend/src/components/screens/LoaderScreen/LoaderScreen.tsx
> [#311]: Ligretto loader screen scrollbars

- apps/ligretto-gameplay-backend/src/socket-io-server.ts
> [#239] Add a gameplay-backend health check

- apps/ligretto-gameplay-backend/src/socket-io-server.ts
> [#353]: Fix ligretto-gameplay-backend graceful shutdown

- .deploy/blog.deploy.yml
- .docker/Blog_Dockerfile
- .docker/Blog_Dockerfile.dockerignore
- .github/workflows/blog-deploy.yml
- .github/workflows/ligretto-deploy.yml
- README.md
- apps/blog/next.config.js
- apps/blog/package.json
- apps/gamehub-client/package.json
- yarn.lock
> [#198]: Blog release workflow

- apps/blog/src/components/ExternalLink/ExternalLink.tsx
> [#393]: Blog. External link underline

- apps/auth-front/src/pages/profile/ProfilePage.tsx
- apps/auth-front/src/pages/profile/ProfilePage.types.ts
- apps/auth-front/src/pages/profile/useProfileValidation.ts
Задизейблила кнопку если при валидации возникли ошибки, в figma не нашла описание поведения, но вроде логично.
> [#415] Ligretto: fix username validation

- .deploy/ligretto.deploy.yml
- apps/ligretto-frontend/src/ducks/game/slice.ts
- apps/ligretto-gameplay-backend/src/controllers/__tests__/__snapshots__/games-contoller.spec.ts.snap
- apps/ligretto-gameplay-backend/src/entities/game/game.service.ts
- apps/ligretto-gameplay-backend/src/entities/playground/playground.repo.ts
- apps/ligretto-gameplay-backend/src/entities/playground/playground.service.ts
- apps/ligretto-gameplay-backend/src/gameplay/gameplay.ts
- packages/ligretto-shared/src/types.ts
> [#433]: Ligretto. Restrict put more than visible cards

- apps/blog/src/components/InstagramPost/InstagramPostFallback.ts
- apps/blog/src/components/InstagramPost/InstagramPostFallback.tsx
- apps/blog/src/components/InstagramPost/index.ts
> [#438]: Add InstagramPostFallback

- apps/blog/content/posts/what-is-memebattle.en.mdx
- apps/blog/content/posts/what-is-memebattle.ru.mdx
- apps/blog/tailwind.config.js
Добавил стили в компонент открывашки опираясь на дизайн [в Фигме](https://www.figma.com/file/jsSsetyPx0r5ams0nir2CP/Blog?type=design&node-id=827-277&mode=design&t=7kzuG32qvUKZ2jBo-4)
Добавил путь к контэнту в конфиге tailwind
Картинки пока не кликабельны, планируется отдельный компонент для этого
> [#455] styled images in Details block

- apps/blog/next.config.js
- apps/blog/package.json
- apps/gamehub-client/next.config.js
- apps/gamehub-client/package.json
- yarn.lock
Обновил до 14 версии, вроде все работает, убрал experimental options из next.config
Попробовал завести turbo, не завелся
Если я правильно понял доку, то он пока работает только со стандартными плагинами
> [#459] update Blog and Gamehub-client to NextJS v14

- .deploy/ligretto.deploy.yml
- .docker/Ligretto-core-backend_Dockerfile
- apps/ligretto-core-backend/package.json
> [#499]: ligretto-core use managed db

- apps/ligretto-frontend/src/app/routes/Routes.tsx
- apps/ligretto-frontend/src/features/player/index.ts
- apps/ligretto-frontend/src/features/player/ui/Opponent/Opponent.tsx
- apps/ligretto-frontend/src/features/player/ui/Opponent/index.ts
- apps/ligretto-frontend/src/pages/game/GamePage.tsx
- apps/ligretto-frontend/src/pages/onboarding/OnboardingPage.tsx
- apps/ligretto-frontend/src/shared/constants/router-constants.ts
- apps/ligretto-frontend/src/shared/ui/Overlay/Overlay.tsx
- apps/ligretto-frontend/src/shared/ui/Overlay/index.ts
> [#497]: onboarding ui
